FROM ubuntu:20.04

RUN apt update && apt install -y \
	apt-utils \
	curl \
	git \
	python3-pip \
	tftpd-hpa \
	vim \
	wget \
&& rm -rf /var/lib/apt/lists/*
RUN pip3 install --upgrade pip \
	keyring \
	keyrings.alt \
	netmiko
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C99B11DEB97541F0
RUN apt-add-repository https://cli.github.com/packages
RUN apt update && apt install gh
RUN useradd -ms /bin/bash siteadmin && su siteadmin
RUN mkdir /home/siteadmin/actions-runner && mkdir /home/siteadmin/actions-runner/network-automation-github-actions
