FROM ubuntu:20.04

RUN apt update && apt install -y \
	apt-utils \
	curl \
	git \
	python3-pip \
	tftpd-hpa \
	vim \
	wget \
&& rm -rf /var/lib/apt/lists/*
RUN pip3 install --upgrade pip \
	keyring \
	keyrings.alt \
	netmiko